
** Setting up a workstation for notebooks and spike sorting

   Base system: Debian, Ubuntu, Mint

   Install core packages: =apt-get install git g++ cmake libqt4-dev libqtwebkit-dev jupyter-notebook python3-venv=

   Download source for LibKlustersShared and Klusters from
   http://neurosuite.sourceforge.net/GNULinux.html and follow instructions.

   See ../README.md for instructions on setting up the notebook server.

** Creating a new docker image

   after committing your changes to git, run =docker build -t
   dmeliza/comp-neurosci:latest .=, replacing <hash> with the short hash of your
   last commit.

   Then run the following to start the docker container for testing.

   =docker run --rm --name comp-neurosci -p 8888:8888 -v "$PWD":/home/jovyan/work dmeliza/comp-neurosci:latest=

** Notes from Spring 2020 for next iteration

   Reconcile notebook names and week numbers

   Need to reorder some of the conceptual material. It makes more sense to
   discuss rate models (LTI systems), then spikes.

   Need to set up a parallel set of notebook for programming concepts. Introduce
   students to numpy arrays and plotting early. Students with some programming
   experience often fail to solve problems efficiently because they are trying
   to use for loops when array broadcasting is more effective.

   Try to steer students away from classes toward data structures

   Notebook 6A: add a demo to show how LNP model predicts orientation tuning
   before doing RF estimation
